<?php

namespace WpAdldap2\Admin\Views;

use WpAdldap2\Admin\Helpers\HtmlForm;
use WpAdldap2\Settings;
use WpAdldap2\UserProfile;

class AdminForm extends HtmlForm {

	protected $_html = [];

	public function __toString() {

		return $this->form( parent::__toString() ); // TODO: Change the autogenerated stub
	}


	public function printLdapSettings() {
		$hosts = (array) Settings::getHosts();

		return $this->table( [
			$this->inputSetting( Settings::getConfigNameOfHosts() . '[0]', 'Host 1', isset( $hosts[0] ) ? $hosts[0] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfHosts() . '[1]', 'Host 2', isset( $hosts[1] ) ? $hosts[1] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfHosts() . '[2]', 'Host 3', isset( $hosts[2] ) ? $hosts[2] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfHosts() . '[3]', 'Host 4', isset( $hosts[3] ) ? $hosts[3] : '', '' ),

			$this->inputSetting( Settings::getConfigNameOfPort(), 'Port', Settings::getPort(), '' ),
			$this->inputSetting( Settings::getConfigNameOfUsername(), 'Username', Settings::getUsername(), '' ),
			$this->inputSetting( Settings::getConfigNameOfPassword(), 'Password', Settings::getPassword(), '' ),
		] );
	}

	public function printFieldsToSync() {
		//username	email	nicename	nickname	Name	display_name	first_name	last_name	Cargo	Sucursal	Ubicación	Orden	Dependencia	Dependencia 2	Aniversario en Renta Nacional	Cumpleaños	Anexo	Asistente
		return $this->table( array_map( function ( $f ) {
			$name = $f->name;

			return $this->inputSetting( Settings::getConfigNameOfMap() . "[$name]", $name, Settings::getADField( $name ), '' );

		}, ( new UserProfile )->getUserFields() ) );
	}

	public function printFieldsToMatch() {
		$match = (array) Settings::getMatch();

		return $this->table( [
			$this->inputSetting( Settings::getConfigNameOfMatch() . '[0][Ldap]', 'Ldap 1', isset( $match[0][0] ) ? $match[0]['Ldap'] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfMatch() . '[0][wp]', 'Wp 1', isset( $match[0][0] ) ? $match[0]['wp'] : '', '' ),

			$this->inputSetting( Settings::getConfigNameOfMatch() . '[1][Ldap]', 'Ldap 2', isset( $match[1][0] ) ? $match[1]['Ldap'] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfMatch() . '[1][wp]', 'Wp 2', isset( $match[1][0] ) ? $match[1]['wp'] : '', '' ),

			$this->inputSetting( Settings::getConfigNameOfMatch() . '[2][Ldap]', 'Ldap 3', isset( $match[2][0] ) ? $match[2]['Ldap'] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfMatch() . '[2][wp]', 'Wp 3', isset( $match[2][0] ) ? $match[2]['wp'] : '', '' ),

			$this->inputSetting( Settings::getConfigNameOfMatch() . '[3][Ldap]', 'Ldap 4', isset( $match[3][0] ) ? $match[3]['Ldap'] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfMatch() . '[3][wp]', 'Wp 4', isset( $match[3][0] ) ? $match[3]['wp'] : '', '' ),


		] );
	}

	public function printLdapFilters() {
		$basedn = (array) Settings::getBasedn();

		return $this->table( [
			$this->inputSetting( Settings::getConfigNameOfBasedn() . '[0]', 'Filter 1', isset( $basedn[0] ) ? $basedn[0] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfBasedn() . '[1]', 'Filter 2', isset( $basedn[1] ) ? $basedn[1] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfBasedn() . '[2]', 'Filter 3', isset( $basedn[2] ) ? $basedn[2] : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfBasedn() . '[3]', 'Filter 4', isset( $basedn[3] ) ? $basedn[3] : '', '' ),

		] );
	}


}